### ISSUE TITLE
Wireframe - Enterprise Detail

### ISSUE THREAD

**Issue by quimpm** [commed-it/mobile-app#12]
# Screen
A screen of Enterprise Detail must be done in JustInMind.
## What has to be done
The screen is specified in the state diagram image below.
![State Diagram](https://raw.githubusercontent.com/commed-it/docs/main/17-nov/img/stateapp.png)

It must show:
- Enterprise name
- Enterprise contact info
- Enterprise description

**Comment by Oriolac** [comment]
Yassine has done it.
