### ISSUE TITLE
Implementation of SearcherView

### ISSUE THREAD

**Issue by sergisi** [commed-it/mobile-app#42]
# Screen

A screen of SearcherView must be done in flutter.
## What has to be done

The screen is specified in the state diagram image below.
![State Diagram](https://raw.githubusercontent.com/commed-it/docs/main/17-nov/img/stateapp.png)

And it should be a text field input and a list of the historic searches that have been done before.

## What needs to be tested
+ It works
+ It displays the text input
+ The text input is working
+ When clicking a recommendation, the text field updates
+ You can delete the history with a button

**Comment by Oriolac** [comment]
Done in #43
